"""Output writers: PDF, HTML, and Markdown generation."""

from pathlib import Path

from fpdf import FPDF

from utils import sanitize_for_pdf


class TranscriptPDF(FPDF):
    """Custom PDF class with header, chapter title, and body helpers."""

    def header(self) -> None:
        self.set_font("Helvetica", "B", 12)
        self.cell(0, 10, self.doc_title, ln=True, align="C")
        self.ln(2)

    def chapter_title(self, title: str) -> None:
        self.set_font("Helvetica", "B", 14)
        self.set_fill_color(230, 230, 230)
        self.cell(0, 10, title, ln=True, fill=True)
        self.ln(4)

    def chapter_body(self, body: str) -> None:
        self.set_font("Helvetica", "", 11)
        self.multi_cell(0, 6, body)
        self.ln()


def write_html(
    title: str,
    summary_100: str,
    summary_400: str,
    out_path: Path,
) -> None:
    """Write a clean HTML page with summaries only.
    Full transcript is in the Markdown file.
    """
    import mistune
    import html as html_mod

    convert = mistune.html
    t = html_mod.escape(title)
    s100_html = convert(summary_100)
    s400_html = convert(summary_400)

    page = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{t} — Transcript</title>
<style>
  * {{ margin: 0; padding: 0; box-sizing: border-box; }}
  body {{
    font-family: system-ui, -apple-system, 'Segoe UI', Roboto, sans-serif;
    background: #fafafa;
    color: #1a1a2e;
    line-height: 1.7;
    padding: 2rem;
  }}
  .container {{
    max-width: 800px;
    margin: 0 auto;
    background: #fff;
    border-radius: 12px;
    padding: 2.5rem;
    box-shadow: 0 1px 8px rgba(0,0,0,0.06);
    border: 1px solid #eaeaea;
  }}
  h1 {{
    font-size: 1.6rem;
    margin-bottom: 0.25rem;
    color: #111;
  }}
  .subtitle {{
    color: #666;
    font-size: 0.9rem;
    margin-bottom: 2rem;
    border-bottom: 1px solid #eee;
    padding-bottom: 1rem;
  }}
  h2 {{
    font-size: 1.15rem;
    margin: 1.8rem 0 0.6rem;
    color: #333;
    background: #f0f4ff;
    padding: 0.4rem 0.8rem;
    border-radius: 6px;
  }}
  p {{ margin-bottom: 1rem; }}
  .footer {{
    margin-top: 2rem;
    padding-top: 1rem;
    border-top: 1px solid #eee;
    font-size: 0.8rem;
    color: #999;
  }}
</style>
</head>
<body>
<div class="container">
  <h1>{t}</h1>
  <div class="subtitle">AI-Generated Transcript &amp; Summaries</div>

  <h2>100-Word Summary</h2>
  {s100_html}

  <h2>400-Word Summary</h2>
  {s400_html}

  <p class="footer">Generated by transcribe-av-to-pdf &mdash; Local summarization via LM Studio</p>
</div>
</body>
</html>"""
    out_path.write_text(page, encoding="utf-8")


def write_markdown(
    title: str,
    summary_100: str,
    summary_400: str,
    transcript: str,
    out_path: Path,
) -> None:
    """Write a Markdown document with summaries and full transcript."""
    lines = [
        f"# {title}",
        "",
        "*AI-Generated Transcript &amp; Summaries*",
        "",
        "---",
        "",
        "## 100-Word Summary",
        "",
        summary_100,
        "",
        "## 400-Word Summary",
        "",
        summary_400,
        "",
        "## Full Transcript",
        "",
        transcript,
        "",
        "---",
        "*Generated by transcribe-av-to-pdf &mdash; Local summarization via LM Studio*",
        "",
    ]
    out_path.write_text("\n".join(lines), encoding="utf-8")


def write_pdf(
    title: str,
    summary_100: str,
    summary_400: str,
    out_path: Path,
) -> None:
    """Write a PDF with title page and two summary sections."""
    pdf = TranscriptPDF()
    pdf.doc_title = sanitize_for_pdf(title)
    pdf.set_auto_page_break(auto=True, margin=15)

    pdf.add_page()
    pdf.set_font("Helvetica", "B", 20)
    pdf.ln(60)
    pdf.multi_cell(0, 12, pdf.doc_title, align="C")
    pdf.set_font("Helvetica", "", 12)
    pdf.ln(10)
    pdf.cell(0, 10, "AI-Generated Transcript & Summaries", new_x="LMARGIN", new_y="NEXT", align="C")

    pdf.add_page()
    pdf.chapter_title("100-Word Summary")
    pdf.chapter_body(sanitize_for_pdf(summary_100))

    pdf.add_page()
    pdf.chapter_title("400-Word Summary")
    pdf.chapter_body(sanitize_for_pdf(summary_400))

    pdf.output(str(out_path))
